import { Container, Typography, Box, Paper } from '@mui/material';
import Layout from './Layout';

const Privacy = () => {
  return (
    <Layout>
      <Container maxWidth="md" sx={{ py: 8 }}>
        <Paper sx={{
          p: 6,
          background: 'rgba(255, 255, 255, 0.05)',
          backdropFilter: 'blur(20px)',
          border: '1px solid rgba(255, 255, 255, 0.1)',
          borderRadius: 4
        }}>
          <Typography variant="h2" sx={{
            color: 'white',
            fontWeight: 900,
            mb: 4,
            textAlign: 'center',
            fontSize: { xs: '2.5rem', md: '3.5rem' },
            letterSpacing: '-1px'
          }}>
            Privacy Policy
          </Typography>

          <Typography variant="h6" sx={{
            color: 'rgba(255, 255, 255, 0.7)',
            mb: 6,
            textAlign: 'center',
            lineHeight: 1.8
          }}>
            Last updated: October 27, 2024
          </Typography>

          <Box sx={{ color: 'rgba(255, 255, 255, 0.9)', lineHeight: 1.8 }}>
            <Typography variant="h4" sx={{ color: 'white', fontWeight: 700, mb: 3, mt: 4 }}>
              1. Information We Collect
            </Typography>
            <Typography variant="body1" sx={{ mb: 4 }}>
              We collect information you provide directly to us, such as when you create an account, use our services, or contact us for support. This may include your name, email address, and social media account information.
            </Typography>

            <Typography variant="h4" sx={{ color: 'white', fontWeight: 700, mb: 3, mt: 4 }}>
              2. How We Use Your Information
            </Typography>
            <Typography variant="body1" sx={{ mb: 4 }}>
              We use the information we collect to:
            </Typography>
            <Box sx={{ pl: 4, mb: 4 }}>
              <Typography variant="body1" sx={{ mb: 2 }}>• Provide, maintain, and improve our services</Typography>
              <Typography variant="body1" sx={{ mb: 2 }}>• Process transactions and send related information</Typography>
              <Typography variant="body1" sx={{ mb: 2 }}>• Send technical notices, updates, security alerts, and support messages</Typography>
              <Typography variant="body1" sx={{ mb: 2 }}>• Respond to your comments, questions, and requests</Typography>
              <Typography variant="body1" sx={{ mb: 2 }}>• Communicate with you about products, services, offers, and events</Typography>
            </Box>

            <Typography variant="h4" sx={{ color: 'white', fontWeight: 700, mb: 3, mt: 4 }}>
              3. Information Sharing
            </Typography>
            <Typography variant="body1" sx={{ mb: 4 }}>
              We do not sell, trade, or otherwise transfer your personal information to third parties without your consent, except as described in this policy. We may share your information in the following circumstances:
            </Typography>
            <Box sx={{ pl: 4, mb: 4 }}>
              <Typography variant="body1" sx={{ mb: 2 }}>• With service providers who assist us in operating our platform</Typography>
              <Typography variant="body1" sx={{ mb: 2 }}>• When required by law or to protect our rights</Typography>
              <Typography variant="body1" sx={{ mb: 2 }}>• In connection with a business transfer or bankruptcy</Typography>
              <Typography variant="body1" sx={{ mb: 2 }}>• With your explicit consent</Typography>
            </Box>

            <Typography variant="h4" sx={{ color: 'white', fontWeight: 700, mb: 3, mt: 4 }}>
              4. Data Security
            </Typography>
            <Typography variant="body1" sx={{ mb: 4 }}>
              We implement appropriate technical and organizational measures to protect your personal information against unauthorized access, alteration, disclosure, or destruction. However, no method of transmission over the internet is 100% secure.
            </Typography>

            <Typography variant="h4" sx={{ color: 'white', fontWeight: 700, mb: 3, mt: 4 }}>
              5. Social Media Integration
            </Typography>
            <Typography variant="body1" sx={{ mb: 4 }}>
              When you connect your social media accounts, we use secure OAuth connections. We never store your social media passwords. We only access the information necessary to provide our services and post content on your behalf.
            </Typography>

            <Typography variant="h4" sx={{ color: 'white', fontWeight: 700, mb: 3, mt: 4 }}>
              6. AI Content Generation
            </Typography>
            <Typography variant="body1" sx={{ mb: 4 }}>
              Content generated by our AI is based on your profile information and selected topics. We do not use your personal data to train our AI models or share it with third parties for training purposes.
            </Typography>

            <Typography variant="h4" sx={{ color: 'white', fontWeight: 700, mb: 3, mt: 4 }}>
              7. Data Retention
            </Typography>
            <Typography variant="body1" sx={{ mb: 4 }}>
              We retain your personal information for as long as necessary to provide our services and fulfill the purposes outlined in this policy, unless a longer retention period is required by law.
            </Typography>

            <Typography variant="h4" sx={{ color: 'white', fontWeight: 700, mb: 3, mt: 4 }}>
              8. Your Rights
            </Typography>
            <Typography variant="body1" sx={{ mb: 4 }}>
              Depending on your location, you may have certain rights regarding your personal information, including:
            </Typography>
            <Box sx={{ pl: 4, mb: 4 }}>
              <Typography variant="body1" sx={{ mb: 2 }}>• Access to your personal information</Typography>
              <Typography variant="body1" sx={{ mb: 2 }}>• Correction of inaccurate information</Typography>
              <Typography variant="body1" sx={{ mb: 2 }}>• Deletion of your personal information</Typography>
              <Typography variant="body1" sx={{ mb: 2 }}>• Restriction or objection to processing</Typography>
              <Typography variant="body1" sx={{ mb: 2 }}>• Data portability</Typography>
            </Box>

            <Typography variant="h4" sx={{ color: 'white', fontWeight: 700, mb: 3, mt: 4 }}>
              9. Cookies and Tracking
            </Typography>
            <Typography variant="body1" sx={{ mb: 4 }}>
              We use cookies and similar technologies to enhance your experience, analyze usage, and assist in our marketing efforts. You can control cookie settings through your browser preferences.
            </Typography>

            <Typography variant="h4" sx={{ color: 'white', fontWeight: 700, mb: 3, mt: 4 }}>
              10. International Data Transfers
            </Typography>
            <Typography variant="body1" sx={{ mb: 4 }}>
              Your information may be transferred to and processed in countries other than your own. We ensure appropriate safeguards are in place to protect your personal information during such transfers.
            </Typography>

            <Typography variant="h4" sx={{ color: 'white', fontWeight: 700, mb: 3, mt: 4 }}>
              11. Children's Privacy
            </Typography>
            <Typography variant="body1" sx={{ mb: 4 }}>
              Our services are not intended for children under 13. We do not knowingly collect personal information from children under 13. If we become aware that we have collected such information, we will take steps to delete it.
            </Typography>

            <Typography variant="h4" sx={{ color: 'white', fontWeight: 700, mb: 3, mt: 4 }}>
              12. Changes to This Policy
            </Typography>
            <Typography variant="body1" sx={{ mb: 4 }}>
              We may update this Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the "Last updated" date.
            </Typography>

            <Typography variant="h4" sx={{ color: 'white', fontWeight: 700, mb: 3, mt: 4 }}>
              13. Contact Us
            </Typography>
            <Typography variant="body1" sx={{ mb: 4 }}>
              If you have any questions about this Privacy Policy, please contact us at privacy@autopost.ai.
            </Typography>
          </Box>
        </Paper>
      </Container>
    </Layout>
  );
};

export default Privacy;