import Layout from './Layout';

const Privacy = () => {
  return (
    <Layout>
      <div className="max-w-3xl mx-auto px-4 py-12 md:py-16">
        <div className="bg-white border border-slate-200/80 rounded-2xl p-6 md:p-10 shadow-xs">
          <h1 className="text-3xl md:text-4xl font-extrabold text-slate-900 tracking-tight text-center mb-2">
            Privacy Policy
          </h1>
          <p className="text-xs font-semibold text-slate-400 text-center mb-8">
            Last updated: October 27, 2024
          </p>

          <div className="text-slate-600 text-sm leading-relaxed space-y-6">
            <div>
              <h2 className="text-lg font-bold text-slate-900 mb-2">1. Information We Collect</h2>
              <p>
                We collect information you provide directly to us, such as when you create an account, use our services, or contact us for support. This may include your name, email address, and social media account information.
              </p>
            </div>

            <div>
              <h2 className="text-lg font-bold text-slate-900 mb-2">2. How We Use Your Information</h2>
              <p>
                We use the information we collect to:
              </p>
              <ul className="list-disc pl-5 mt-2 space-y-1 text-slate-500">
                <li>Provide, maintain, and improve our services</li>
                <li>Process transactions and send related information</li>
                <li>Send technical notices, updates, security alerts, and support messages</li>
                <li>Respond to your comments, questions, and requests</li>
                <li>Communicate with you about products, services, offers, and events</li>
              </ul>
            </div>

            <div>
              <h2 className="text-lg font-bold text-slate-900 mb-2">3. Information Sharing</h2>
              <p>
                We do not sell, trade, or otherwise transfer your personal information to third parties without your consent, except as described in this policy. We may share your information in the following circumstances:
              </p>
              <ul className="list-disc pl-5 mt-2 space-y-1 text-slate-500">
                <li>With service providers who assist us in operating our platform</li>
                <li>When required by law or to protect our rights</li>
                <li>In connection with a business transfer or bankruptcy</li>
                <li>With your explicit consent</li>
              </ul>
            </div>

            <div>
              <h2 className="text-lg font-bold text-slate-900 mb-2">4. Data Security</h2>
              <p>
                We implement appropriate technical and organizational measures to protect your personal information against unauthorized access, alteration, disclosure, or destruction. However, no method of transmission over the internet is 100% secure.
              </p>
            </div>

            <div>
              <h2 className="text-lg font-bold text-slate-900 mb-2">5. Social Media Integration</h2>
              <p>
                When you connect your social media accounts, we use secure OAuth connections. We never store your social media passwords. We only access the information necessary to provide our services and post content on your behalf.
              </p>
            </div>

            <div>
              <h2 className="text-lg font-bold text-slate-900 mb-2">6. AI Content Generation</h2>
              <p>
                Content generated by our AI is based on your profile information and selected topics. We do not use your personal data to train our AI models or share it with third parties for training purposes.
              </p>
            </div>

            <div>
              <h2 className="text-lg font-bold text-slate-900 mb-2">7. Data Retention</h2>
              <p>
                We retain your personal information for as long as necessary to provide our services and fulfill the purposes outlined in this policy, unless a longer retention period is required by law.
              </p>
            </div>

            <div>
              <h2 className="text-lg font-bold text-slate-900 mb-2">8. Your Rights</h2>
              <p>
                Depending on your location, you may have certain rights regarding your personal information, including:
              </p>
              <ul className="list-disc pl-5 mt-2 space-y-1 text-slate-500">
                <li>Access to your personal information</li>
                <li>Correction of inaccurate information</li>
                <li>Deletion of your personal information</li>
                <li>Restriction or objection to processing</li>
                <li>Data portability</li>
              </ul>
            </div>

            <div>
              <h2 className="text-lg font-bold text-slate-900 mb-2">9. Cookies and Tracking</h2>
              <p>
                We use cookies and similar technologies to enhance your experience, analyze usage, and assist in our marketing efforts. You can control cookie settings through your browser preferences.
              </p>
            </div>

            <div>
              <h2 className="text-lg font-bold text-slate-900 mb-2">10. International Data Transfers</h2>
              <p>
                Your information may be transferred to and processed in countries other than your own. We ensure appropriate safeguards are in place to protect your personal information during such transfers.
              </p>
            </div>

            <div>
              <h2 className="text-lg font-bold text-slate-900 mb-2">11. Children's Privacy</h2>
              <p>
                Our services are not intended for children under 13. We do not knowingly collect personal information from children under 13. If we become aware that we have collected such information, we will take steps to delete it.
              </p>
            </div>

            <div>
              <h2 className="text-lg font-bold text-slate-900 mb-2">12. Changes to This Policy</h2>
              <p>
                We may update this Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the "Last updated" date.
              </p>
            </div>

            <div>
              <h2 className="text-lg font-bold text-slate-900 mb-2">13. Contact Us</h2>
              <p>
                If you have any questions about this Privacy Policy, please contact us at privacy@autopost.ai.
              </p>
            </div>
          </div>
        </div>
      </div>
    </Layout>
  );
};

export default Privacy;