import Layout from './Layout';

const Terms = () => {
  return (
    <Layout>
      <div className="max-w-3xl mx-auto px-4 py-12 md:py-16">
        <div className="bg-white border border-slate-200/80 rounded-2xl p-6 md:p-10 shadow-xs">
          <h1 className="text-3xl md:text-4xl font-extrabold text-slate-900 tracking-tight text-center mb-2">
            Terms of Service
          </h1>
          <p className="text-xs font-semibold text-slate-400 text-center mb-8">
            Last updated: October 27, 2024
          </p>

          <div className="text-slate-600 text-sm leading-relaxed space-y-6">
            <div>
              <h2 className="text-lg font-bold text-slate-900 mb-2">1. Acceptance of Terms</h2>
              <p>
                By accessing and using PostNexus, you accept and agree to be bound by the terms and provision of this agreement.
              </p>
            </div>

            <div>
              <h2 className="text-lg font-bold text-slate-900 mb-2">2. Use License</h2>
              <p>
                Permission is granted to temporarily use PostNexus for personal, non-commercial transitory viewing only. This is the grant of a license, not a transfer of title, and under this license you may not:
              </p>
              <ul className="list-disc pl-5 mt-2 space-y-1 text-slate-500">
                <li>Modify or copy the materials</li>
                <li>Use the materials for any commercial purpose or for any public display</li>
                <li>Attempt to decompile or reverse engineer any software contained on PostNexus</li>
                <li>Remove any copyright or other proprietary notations from the materials</li>
              </ul>
            </div>

            <div>
              <h2 className="text-lg font-bold text-slate-900 mb-2">3. Service Description</h2>
              <p>
                PostNexus provides AI-powered social media content generation and automation services. We reserve the right to modify or discontinue the service at any time without notice.
              </p>
            </div>

            <div>
              <h2 className="text-lg font-bold text-slate-900 mb-2">4. User Responsibilities</h2>
              <p>
                You are responsible for maintaining the confidentiality of your account and password. You agree to accept responsibility for all activities that occur under your account.
              </p>
            </div>

            <div>
              <h2 className="text-lg font-bold text-slate-900 mb-2">5. Content Ownership</h2>
              <p>
                All content generated by our AI remains your property. You retain full rights to use, modify, and distribute the generated content as you see fit.
              </p>
            </div>

            <div>
              <h2 className="text-lg font-bold text-slate-900 mb-2">6. Limitation of Liability</h2>
              <p>
                In no event shall PostNexus or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use PostNexus.
              </p>
            </div>

            <div>
              <h2 className="text-lg font-bold text-slate-900 mb-2">7. Termination</h2>
              <p>
                We may terminate or suspend your account immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.
              </p>
            </div>

            <div>
              <h2 className="text-lg font-bold text-slate-900 mb-2">8. Governing Law</h2>
              <p>
                These terms and conditions are governed by and construed in accordance with applicable laws, and any disputes relating to these terms and conditions will be subject to the exclusive jurisdiction of the courts.
              </p>
            </div>

            <div>
              <h2 className="text-lg font-bold text-slate-900 mb-2">9. Changes to Terms</h2>
              <p>
                We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material, we will try to provide at least 30 days notice prior to any new terms taking effect.
              </p>
            </div>

            <div>
              <h2 className="text-lg font-bold text-slate-900 mb-2">10. Contact Information</h2>
              <p>
                If you have any questions about these Terms of Service, please contact us at legal@autopost.ai.
              </p>
            </div>
          </div>
        </div>
      </div>
    </Layout>
  );
};

export default Terms;