import { Container, Typography, Box, Paper } from '@mui/material';
import Layout from './Layout';

const Terms = () => {
  return (
    <Layout>
      <Container maxWidth="md" sx={{ py: 8 }}>
        <Paper sx={{
          p: 6,
          background: 'rgba(255, 255, 255, 0.05)',
          backdropFilter: 'blur(20px)',
          border: '1px solid rgba(255, 255, 255, 0.1)',
          borderRadius: 4
        }}>
          <Typography variant="h2" sx={{
            color: 'white',
            fontWeight: 900,
            mb: 4,
            textAlign: 'center',
            fontSize: { xs: '2.5rem', md: '3.5rem' },
            letterSpacing: '-1px'
          }}>
            Terms of Service
          </Typography>

          <Typography variant="h6" sx={{
            color: 'rgba(255, 255, 255, 0.7)',
            mb: 6,
            textAlign: 'center',
            lineHeight: 1.8
          }}>
            Last updated: October 27, 2024
          </Typography>

          <Box sx={{ color: 'rgba(255, 255, 255, 0.9)', lineHeight: 1.8 }}>
            <Typography variant="h4" sx={{ color: 'white', fontWeight: 700, mb: 3, mt: 4 }}>
              1. Acceptance of Terms
            </Typography>
            <Typography variant="body1" sx={{ mb: 4 }}>
              By accessing and using PostNexus, you accept and agree to be bound by the terms and provision of this agreement.
            </Typography>

            <Typography variant="h4" sx={{ color: 'white', fontWeight: 700, mb: 3, mt: 4 }}>
              2. Use License
            </Typography>
            <Typography variant="body1" sx={{ mb: 4 }}>
              Permission is granted to temporarily use PostNexus for personal, non-commercial transitory viewing only. This is the grant of a license, not a transfer of title, and under this license you may not:
            </Typography>
            <Box sx={{ pl: 4, mb: 4 }}>
              <Typography variant="body1" sx={{ mb: 2 }}>• Modify or copy the materials</Typography>
              <Typography variant="body1" sx={{ mb: 2 }}>• Use the materials for any commercial purpose or for any public display</Typography>
              <Typography variant="body1" sx={{ mb: 2 }}>• Attempt to decompile or reverse engineer any software contained on PostNexus</Typography>
              <Typography variant="body1" sx={{ mb: 2 }}>• Remove any copyright or other proprietary notations from the materials</Typography>
            </Box>

            <Typography variant="h4" sx={{ color: 'white', fontWeight: 700, mb: 3, mt: 4 }}>
              3. Service Description
            </Typography>
            <Typography variant="body1" sx={{ mb: 4 }}>
              PostNexus provides AI-powered social media content generation and automation services. We reserve the right to modify or discontinue the service at any time without notice.
            </Typography>

            <Typography variant="h4" sx={{ color: 'white', fontWeight: 700, mb: 3, mt: 4 }}>
              4. User Responsibilities
            </Typography>
            <Typography variant="body1" sx={{ mb: 4 }}>
              You are responsible for maintaining the confidentiality of your account and password. You agree to accept responsibility for all activities that occur under your account.
            </Typography>

            <Typography variant="h4" sx={{ color: 'white', fontWeight: 700, mb: 3, mt: 4 }}>
              5. Content Ownership
            </Typography>
            <Typography variant="body1" sx={{ mb: 4 }}>
              All content generated by our AI remains your property. You retain full rights to use, modify, and distribute the generated content as you see fit.
            </Typography>

            <Typography variant="h4" sx={{ color: 'white', fontWeight: 700, mb: 3, mt: 4 }}>
              6. Limitation of Liability
            </Typography>
            <Typography variant="body1" sx={{ mb: 4 }}>
              In no event shall PostNexus or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use PostNexus.
            </Typography>

            <Typography variant="h4" sx={{ color: 'white', fontWeight: 700, mb: 3, mt: 4 }}>
              7. Termination
            </Typography>
            <Typography variant="body1" sx={{ mb: 4 }}>
              We may terminate or suspend your account immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.
            </Typography>

            <Typography variant="h4" sx={{ color: 'white', fontWeight: 700, mb: 3, mt: 4 }}>
              8. Governing Law
            </Typography>
            <Typography variant="body1" sx={{ mb: 4 }}>
              These terms and conditions are governed by and construed in accordance with applicable laws, and any disputes relating to these terms and conditions will be subject to the exclusive jurisdiction of the courts.
            </Typography>

            <Typography variant="h4" sx={{ color: 'white', fontWeight: 700, mb: 3, mt: 4 }}>
              9. Changes to Terms
            </Typography>
            <Typography variant="body1" sx={{ mb: 4 }}>
              We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material, we will try to provide at least 30 days notice prior to any new terms taking effect.
            </Typography>

            <Typography variant="h4" sx={{ color: 'white', fontWeight: 700, mb: 3, mt: 4 }}>
              10. Contact Information
            </Typography>
            <Typography variant="body1" sx={{ mb: 4 }}>
              If you have any questions about these Terms of Service, please contact us at legal@autopost.ai.
            </Typography>
          </Box>
        </Paper>
      </Container>
    </Layout>
  );
};

export default Terms;