import { useState, useEffect } from 'react';
import apiService from '../../services/api';

const PreGeneratedPosts = () => {
  const [posts, setPosts] = useState([]);
  const [loading, setLoading] = useState(true);
  const [regenerateDialog, setRegenerateDialog] = useState(false);
  const [currentPostId, setCurrentPostId] = useState(null);
  const [suggestion, setSuggestion] = useState('');
  const [regenerating, setRegenerating] = useState(false);
  const [cancelling, setCancelling] = useState(null);
  const [error, setError] = useState('');

  const fetchPosts = async () => {
    try {
      setLoading(true);
      const res = await apiService.getScheduledPosts({ status: 'scheduled' });
      // Filter for auto-generated only
      const autoPosts = (res.scheduledPosts || []).filter(p => p.type === 'auto-generated');
      setPosts(autoPosts);
    } catch (err) {
      console.error('Failed to fetch posts', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchPosts();
  }, []);

  const handleRegenerateClick = (id) => {
    setCurrentPostId(id);
    setSuggestion('');
    setError('');
    setRegenerateDialog(true);
  };

  const submitRegenerate = async () => {
    if (!suggestion.trim()) return;
    try {
      setRegenerating(true);
      setError('');
      await apiService.regenerateScheduledPost(currentPostId, suggestion);
      setRegenerateDialog(false);
      await fetchPosts();
    } catch (err) {
      setError(err.message || 'Failed to regenerate content');
    } finally {
      setRegenerating(false);
    }
  };

  const handleCancel = async (id) => {
    try {
      setCancelling(id);
      await apiService.cancelScheduledPost(id);
      await fetchPosts();
    } catch (err) {
      console.error('Failed to cancel post', err);
    } finally {
      setCancelling(null);
    }
  };

  if (loading) {
    return (
      <div className="flex justify-center p-8">
        <svg className="animate-spin h-6 w-6 text-indigo-600" fill="none" viewBox="0 0 24 24">
          <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
          <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
        </svg>
      </div>
    );
  }

  return (
    <div className="mt-8 max-w-4xl">
      <h2 className="text-xl font-bold text-slate-900 mb-4">Upcoming Pre-Generated Posts</h2>
      
      {posts.length === 0 ? (
        <div className="p-6 bg-slate-50 border border-slate-200 border-dashed rounded-2xl text-center text-slate-500 text-sm">
          No upcoming pre-generated posts. They will appear here once generated by your schedule.
        </div>
      ) : (
        <div className="space-y-4">
          {posts.map(post => (
            <div key={post.id} className="bg-white border border-slate-200 rounded-xl p-5 shadow-sm">
              <div className="flex justify-between items-start mb-3">
                <div>
                  <span className="inline-block px-2 py-1 bg-indigo-50 text-indigo-700 text-xs font-bold rounded-lg uppercase tracking-wider mb-2">
                    {new Date(post.scheduledAt).toLocaleString(undefined, { dateStyle: 'medium', timeStyle: 'short' })}
                  </span>
                  <div className="flex gap-1.5 mt-1">
                    {post.platforms?.map(p => (
                      <span key={p.id} className="text-[10px] font-bold uppercase tracking-wider text-slate-400 bg-slate-100 px-2 py-0.5 rounded-md">
                        {p.platform}
                      </span>
                    ))}
                  </div>
                </div>
                <div className="flex gap-2">
                  <button 
                    onClick={() => handleRegenerateClick(post.id)}
                    className="text-xs font-semibold text-indigo-600 hover:text-indigo-800 transition-colors bg-indigo-50 hover:bg-indigo-100 px-3 py-1.5 rounded-lg"
                  >
                    Regenerate
                  </button>
                  <button 
                    onClick={() => handleCancel(post.id)}
                    disabled={cancelling === post.id}
                    className="text-xs font-semibold text-rose-600 hover:text-rose-800 transition-colors bg-rose-50 hover:bg-rose-100 px-3 py-1.5 rounded-lg disabled:opacity-50"
                  >
                    {cancelling === post.id ? 'Rejecting...' : 'Reject'}
                  </button>
                </div>
              </div>
              <p className="text-sm text-slate-700 whitespace-pre-wrap">{post.content}</p>
            </div>
          ))}
        </div>
      )}

      {/* Regenerate Dialog */}
      {regenerateDialog && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/40 backdrop-blur-xs">
          <div className="bg-white rounded-2xl border border-slate-200 shadow-xl max-w-md w-full overflow-hidden animate-in fade-in zoom-in-95 duration-150">
            <div className="px-6 py-4 border-b border-slate-100 flex items-center justify-between">
              <h3 className="text-base font-bold text-slate-900">Regenerate Post</h3>
              <button onClick={() => setRegenerateDialog(false)} disabled={regenerating} className="text-slate-400 hover:text-slate-600">
                <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="2">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            </div>
            <div className="p-6">
              <label className="block text-xs font-semibold text-slate-500 mb-2">HOW SHOULD WE CHANGE IT?</label>
              <textarea
                value={suggestion}
                onChange={(e) => setSuggestion(e.target.value)}
                placeholder="e.g. Make it shorter, add a different hook, remove hashtags..."
                className="w-full px-4 py-3 bg-slate-50 border border-slate-200 rounded-xl text-slate-900 text-sm focus:outline-none focus:border-indigo-500 focus:ring-4 focus:ring-indigo-500/10 min-h-[100px] resize-none"
                disabled={regenerating}
              />
              {error && <p className="text-xs text-rose-600 mt-2 font-semibold">{error}</p>}
            </div>
            <div className="px-6 py-4 bg-slate-50/50 border-t border-slate-100 flex justify-end gap-3">
              <button
                onClick={() => setRegenerateDialog(false)}
                disabled={regenerating}
                className="px-4 py-2 rounded-xl text-xs font-semibold text-slate-500 hover:bg-slate-100 hover:text-slate-700 transition-colors"
              >
                Cancel
              </button>
              <button
                onClick={submitRegenerate}
                disabled={regenerating || !suggestion.trim()}
                className="px-4 py-2 bg-indigo-600 hover:bg-indigo-700 disabled:bg-indigo-400 text-white rounded-xl text-xs font-semibold shadow-sm transition-all flex items-center gap-2"
              >
                {regenerating && (
                  <svg className="animate-spin h-3.5 w-3.5 text-white" fill="none" viewBox="0 0 24 24">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
                  </svg>
                )}
                Regenerate
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default PreGeneratedPosts;
